### ISSUE TITLE
Update the guides to remove usage of `.get`

### ISSUE THREAD

**Issue by locks** [emberjs/guides#2303]
In Ember v3.1.0, you can now omit `.get` to retrieve computed properties.

## Tasks
- [ ] Update code samples to remove `.get` where that is possible
- [ ] Explain the situations where `.get` is still required in "The Object Model"
- [ ] Run the codemod in https://github.com/ember-learn/super-rentals and make sure code snippets in the Guides match
