### ISSUE TITLE
Improve Guides organization

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/guides#450]
@locks, @trek, and I have been talking about how to improve the organization of the guide. This is a meta-issue to track all of the things that need to be done to get the guides into a sane organizational state. 

First, here are new sections that need to be created:

- [ ] A tutorial for building your first Ember app (#445)
- [ ] Services (#442)
- [ ] Animations (#448)

Second, here are major changes that need to be made:

- [ ] Models needs some heavy re-organization and updating (#449)
- [ ] Ember CLI needs to be integrated throughout the guides (#410)

The above items are the highest-priority work.
<hr>
In addition, there are a few other things that should be taken care of, but are lower priority:

- [ ] The installation guide needs to cover more scenarios and address common pitfalls
- General organization:
  - [ ] Throughout the guides, we should link to the API docs for more information
  - [ ] Throughout the guides, we should add links to external explanations of concepts like promises, ES6 modules, etc.
  - [ ] Throughout the guides, we should use a consistent example app (eg, a blog)
- Ember CLI stuff:
  - [ ] We need to add info on upgrading
  - [ ] We need to add info on deploying
  - [ ] We need to add info on using stylesheets with Ember CLI
- "Configuring Ember.js" and "Understanding Ember.js"
  - [ ] Potentially move "Disabling Prototype Extensions" into "The Object Model" section
  - [ ] Potentially move "Embedding Applications" into "Routing"
  - [ ] Potentially break up "Debugging" into all of the relevant sections (eg Templates, Controllers, etc)

**Comment by michaelrkn** [comment]
@locks and @trek, can you review and see if this looks okay to you? My thinking is that we work hard to get the stuff above the line done by 2.0, and the stuff below the line by 2.1.

**Comment by michaelrkn** [comment]
This is well underway - I don't think this meta-issue is helpful any more.
